title: 全能TV-保险柜视频漫画娱乐平台

keywords: "全能TV,保险柜视频,保险柜漫画"

description: 全能保险柜旗下品牌全能TV是国内保险柜行业首个集行业视频和行业漫画等娱乐类功能专业化的保险柜视频平台。

url: http://www.qnnsafe.tv

permalink: /:categories/:title.html

relative_permalinks: false

videos:
  全能形象:
    name: image
    屌丝变形记: diao-si
    全能保险柜之天下无贼: tian-xia-wu-zei
    保险柜的故事: bao-xian-gui-de-gu-shi
    家庭安全守护者: an-quan-shou-hu-zhe
  全能文化:
    name: culture
    冠军精神: guan-jun
    香港锁匠学会参观访问: xiang-gang-suo-jiang-xue-hui
    牵手相助贫困小学: ai-xin
    橄榄球精神: gan-lan-qiu
  安防宣传:
    name: safety
    家居安全在哪里: jia-ju-an-quan
    家庭安全守护者: jia-ting-fang-dao
    一台保险柜的诞生: bao-xian-gui-de-dan-sheng
  全能产品:
    name: products
    全能金库系列介绍: product-jin-ku
    防盗保管箱2243使用说明: product-2243
    CX-1625使用说明: product-cx1625
    JD-3340使用说明: product-jd3340
    JD-4538使用说明: product-jd4538
    iBox钢甲小宝使用说明: product-ibox
    LG-2535使用说明: product-lg2535
    钢铁侠GTX845使用说明:
      youku: XNTcyMjEwNDI4
    IA53使用说明:
      youku: XNTcyMjEwNDI4
    高尔夫GLF7042使用说明:
      youku: XNjM3MzUzODk2
    酷宝KB5842使用说明:
      youku: XNjQxNjE5MDA0
    欧若拉AI5842使用说明:
      youku: XNTcyMjEwNDI4
    test:
      youku: XNTcyMjEwNDI4
    test:
      youku: XNTcyMjEwNDI4
  全能漫画:
    name: animations
    屌丝变形记: diao-si

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  cache: true
  cache_assets: true
  gzip: []

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Rakefile
  - README.md
